stages:
  - build
  - docker
  - devops

build:
  image: node:16.14.2
  tags:
    - wutong-devops
  stage: build
  script:
    - yarn config set registry https://registry.npm.taobao.org
    - yarn config set disturl https://npm.taobao.org/dist
    - yarn config set electron_mirror https://npm.taobao.org/mirrors/electron/
    - yarn install
    - yarn run build
  only:
    variables:
      - ${{auto.build}} == "true"
  artifacts:
    paths:
      - dist


docker:
  image: swr.cn-north-4.myhuaweicloud.com/wutong/docker:19.03.13
  tags:
    - wutong-devops
  stage: docker
  script:
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} ${HARBOR_SCHEMAL}//${HARBOR_URL}
    - docker build -t  ${HARBOR_URL}/${TEAM_CODE}/{{service.code}}:${DEVOPS_VERSION} .
    - docker push ${HARBOR_URL}/${TEAM_CODE}/{{service.code}}:${DEVOPS_VERSION}
  only:
    variables:
      - ${{auto.build}} == "true"

devops:
  image: node:16.14.2
  tags:
    - wutong-devops
  stage: devops
  script:
    - http_status_code=`curl -o /dev/null -s -m 10 --connect-timeout 10 -w %{http_code} "${GATEWAY}/hook/ci?gitlabProjectId=${CI_PROJECT_ID}&version=${DEVOPS_VERSION}&commit=${CI_COMMIT_SHA}&branch=${CI_COMMIT_REF_SLUG}"`
    - |
      if [ "$http_status_code" != "200" ]; then
      echo $http_status_code
      echo "上传应用服务版本失败"
      exit 1
      fi
  only:
    variables:
      - ${{auto.build}} == "true"
