stages:
  - build
  - docker
  - devops

build:
  image: maven:3.6.3-openjdk-8
  stage: build
  script:
    - mvn clean package -pl ${package_path} -am -DskipTests=true
  only:
    variables:
      - ${{auto.build}} == "true"
  artifacts:
    paths:
      - ${package_path}/target/${jar_name}.jar

docker:
  stage: docker
  image: docker:20.10
  script:
    - mkdir target
    - cp ${package_path}/target/${jar_name}.jar target/app.jar
    - docker login -u  ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} ${HARBOR_SCHEMAL}//${HARBOR_URL}
    - docker build -t  ${HARBOR_URL}/${TEAM_CODE}/${MODULE}:${DEVOPS_VERSION} .
    - docker push ${HARBOR_URL}/${TEAM_CODE}/${MODULE}:${DEVOPS_VERSION}
  only:
    variables:
      - ${{auto.build}} == "true"

devops:
  stage: devops
  image: maven:3.6.3-openjdk-8
  script:
    - http_status_code=`curl -o /dev/null -s -m 10 --connect-timeout 10 -w %{http_code} "${GATEWAY}/hook/ci?gitlabProjectId=${CI_PROJECT_ID}&version=${DEVOPS_VERSION}&commit=${CI_COMMIT_SHA}&branch=${CI_COMMIT_REF_SLUG}&module=${MODULE}"`
    - |
      if [ "$http_status_code" != "200" ]; then
      echo $http_status_code
      echo "上传应用服务版本失败"
      exit 1
      fi
  only:
    variables:
      - ${{auto.build}} == "true"
