stages:
- build
- docker
build:
  image: node:16.14.2
  stage: build
  script:
  - yarn config set registry https://registry.npm.taobao.org
  - yarn config set disturl https://npm.taobao.org/dist
  - yarn config set electron_mirror https://npm.taobao.org/mirrors/electron/
  - yarn install
  - yarn run build
  tags:
  - wutong-devops
  only:
    variables:
    - $plugins_ui == "true"
  artifacts:
    paths:
    - dist
docker:
  image: swr.cn-north-4.myhuaweicloud.com/wutong/docker:19.03.13
  stage: docker
  script:
  - docker login -u ${REPOSITORY_USERNAME} -p ${REPOSITORY_PASSWORD} ${REPOSITORY_URL}
  - docker build -t  ${REPOSITORY_URL}/${ORG}/plugins-ui:1.0 .
  - docker push ${REPOSITORY_URL}/${ORG}/plugins-ui:1.0
  - |-
    http_status_code=`curl -o /dev/null -s -m 10 --connect-timeout 10 -w %{http_code} "${GATEWAY}/hook/ci?gitlabProjectId=${CI_PROJECT_ID}&version=${DEVOPS_VERSION}&commit=${CI_COMMIT_SHA}&branch=${CI_COMMIT_REF_SLUG}&module=${SUB_SERVICE}"`
          if [ "$http_status_code" != "200" ]; then
          echo $http_status_code
          echo "上传应用服务版本失败"
          exit 1
          fi
  tags:
  - wutong-devops
  only:
    variables:
    - $plugins_ui == "true"
