spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:/db/liquibase/master.xml
  datasource:
    name: mysql_db
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DATABASE:pipeline}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 50
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      connectionInitSqls : ["set names utf8mb4;"]
  application:
    name: plugins
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090

###mybatis-plus配置###
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #auto-mapping-behavior: full
    # 开启日志打印 org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath*:com/devops/**/sql/*.xml

plugins:
  backend:
    url : ${BACKEND_URL}
  rainbond:
    url: ${RAINBOND_URL}
    token: ${RAINBOND_TOKEN}
  mybatis:
    show-sql: false

harbor:
  enable: ${HARBOR_ENABLE:false}
  url:  ${HARBOR_URL}
  username: ${HARBOR_USERNAME}
  password: ${HARBOR_PASSWORD}

jobs:
  cron:
    item-stat: 0 0/10 * * * ?

