spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/liquibase/master.xml
  datasource:
    name: mysql_db
    url: jdbc:mysql://${MYSQL_HOST:116.215.232.249}:${MYSQL_PORT:10031}/devops_plugins?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:RH$7PrG&7%P49pv2}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 2
      max-active: 50
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      connectionInitSqls : ["set names utf8mb4;"]
  application:
    name: plugins
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090

###mybatis-plus配置###
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #auto-mapping-behavior: full
    # 开启日志打印 org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath*:com/devops/**/sql/*.xml

plugins:
  backend:
    url : ${BACKEND_URL:http://uiwkij.natappfree.cc}
  rainbond:
    url: ${RAINBOND_URL:http://47.104.161.96:7070/}
    token: ${RAINBOND_TOKEN:0c95fbb69838ffe5c8e5eb67bf011e53c7fc6e86}
  mybatis:
    show-sql: false

harbor:
  enable: ${HARBOR_ENABLE:false}
  url:  ${HARBOR_URL:https://devhub.wutong.talkweb.com.cn}
  username: ${HARBOR_USERNAME:admin}
  password: ${HARBOR_PASSWORD:DevHub2022!new66}

jobs:
  cron:
    item-stat: 0 0/10 * * * ?

